apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-client
  template:
    metadata:
      labels:
        app: grpc-client
    spec:
      containers:
        - name: grpc-client
          image: grpc-client:latest
          imagePullPolicy: Never