apiVersion: v1
kind: Service
metadata:
  name: client
  annotations:
    io.cilium.service/lb-l7: "enabled"
spec:
  type: NodePort
  selector:
    app: grpc-client
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051